# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V0038MetaPlugin(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, name: str=None):  # noqa: E501
        """V0038MetaPlugin - a model defined in Swagger

        :param type: The type of this V0038MetaPlugin.  # noqa: E501
        :type type: str
        :param name: The name of this V0038MetaPlugin.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'type': str,
            'name': str
        }

        self.attribute_map = {
            'type': 'type',
            'name': 'name'
        }
        self._type = type
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'V0038MetaPlugin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0_0_38_meta_plugin of this V0038MetaPlugin.  # noqa: E501
        :rtype: V0038MetaPlugin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this V0038MetaPlugin.


        :return: The type of this V0038MetaPlugin.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this V0038MetaPlugin.


        :param type: The type of this V0038MetaPlugin.
        :type type: str
        """

        self._type = type

    @property
    def name(self) -> str:
        """Gets the name of this V0038MetaPlugin.


        :return: The name of this V0038MetaPlugin.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this V0038MetaPlugin.


        :param name: The name of this V0038MetaPlugin.
        :type name: str
        """

        self._name = name
