# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v0038_meta_slurm_version import V0038MetaSlurmVersion  # noqa: F401,E501
from swagger_server import util


class V0038MetaSlurm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, version: V0038MetaSlurmVersion=None, release: str=None):  # noqa: E501
        """V0038MetaSlurm - a model defined in Swagger

        :param version: The version of this V0038MetaSlurm.  # noqa: E501
        :type version: V0038MetaSlurmVersion
        :param release: The release of this V0038MetaSlurm.  # noqa: E501
        :type release: str
        """
        self.swagger_types = {
            'version': V0038MetaSlurmVersion,
            'release': str
        }

        self.attribute_map = {
            'version': 'version',
            'release': 'release'
        }
        self._version = version
        self._release = release

    @classmethod
    def from_dict(cls, dikt) -> 'V0038MetaSlurm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0_0_38_meta_Slurm of this V0038MetaSlurm.  # noqa: E501
        :rtype: V0038MetaSlurm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> V0038MetaSlurmVersion:
        """Gets the version of this V0038MetaSlurm.


        :return: The version of this V0038MetaSlurm.
        :rtype: V0038MetaSlurmVersion
        """
        return self._version

    @version.setter
    def version(self, version: V0038MetaSlurmVersion):
        """Sets the version of this V0038MetaSlurm.


        :param version: The version of this V0038MetaSlurm.
        :type version: V0038MetaSlurmVersion
        """

        self._version = version

    @property
    def release(self) -> str:
        """Gets the release of this V0038MetaSlurm.

        version specifier  # noqa: E501

        :return: The release of this V0038MetaSlurm.
        :rtype: str
        """
        return self._release

    @release.setter
    def release(self, release: str):
        """Sets the release of this V0038MetaSlurm.

        version specifier  # noqa: E501

        :param release: The release of this V0038MetaSlurm.
        :type release: str
        """

        self._release = release
