# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v0038_error import V0038Error  # noqa: F401,E501
from swagger_server.models.v0038_license import V0038License  # noqa: F401,E501
from swagger_server import util


class V0038Licenses(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, errors: List[V0038Error]=None, licenses: List[V0038License]=None):  # noqa: E501
        """V0038Licenses - a model defined in Swagger

        :param errors: The errors of this V0038Licenses.  # noqa: E501
        :type errors: List[V0038Error]
        :param licenses: The licenses of this V0038Licenses.  # noqa: E501
        :type licenses: List[V0038License]
        """
        self.swagger_types = {
            'errors': List[V0038Error],
            'licenses': List[V0038License]
        }

        self.attribute_map = {
            'errors': 'errors',
            'licenses': 'licenses'
        }
        self._errors = errors
        self._licenses = licenses

    @classmethod
    def from_dict(cls, dikt) -> 'V0038Licenses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0.0.38_licenses of this V0038Licenses.  # noqa: E501
        :rtype: V0038Licenses
        """
        return util.deserialize_model(dikt, cls)

    @property
    def errors(self) -> List[V0038Error]:
        """Gets the errors of this V0038Licenses.

        slurm errors  # noqa: E501

        :return: The errors of this V0038Licenses.
        :rtype: List[V0038Error]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[V0038Error]):
        """Sets the errors of this V0038Licenses.

        slurm errors  # noqa: E501

        :param errors: The errors of this V0038Licenses.
        :type errors: List[V0038Error]
        """

        self._errors = errors

    @property
    def licenses(self) -> List[V0038License]:
        """Gets the licenses of this V0038Licenses.

        licenses info  # noqa: E501

        :return: The licenses of this V0038Licenses.
        :rtype: List[V0038License]
        """
        return self._licenses

    @licenses.setter
    def licenses(self, licenses: List[V0038License]):
        """Sets the licenses of this V0038Licenses.

        licenses info  # noqa: E501

        :param licenses: The licenses of this V0038Licenses.
        :type licenses: List[V0038License]
        """

        self._licenses = licenses
