# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v0038_error import V0038Error  # noqa: F401,E501
from swagger_server.models.v0038_meta import V0038Meta  # noqa: F401,E501
from swagger_server.models.v0038_partition import V0038Partition  # noqa: F401,E501
from swagger_server import util


class V0038PartitionsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, meta: V0038Meta=None, errors: List[V0038Error]=None, partitions: List[V0038Partition]=None):  # noqa: E501
        """V0038PartitionsResponse - a model defined in Swagger

        :param meta: The meta of this V0038PartitionsResponse.  # noqa: E501
        :type meta: V0038Meta
        :param errors: The errors of this V0038PartitionsResponse.  # noqa: E501
        :type errors: List[V0038Error]
        :param partitions: The partitions of this V0038PartitionsResponse.  # noqa: E501
        :type partitions: List[V0038Partition]
        """
        self.swagger_types = {
            'meta': V0038Meta,
            'errors': List[V0038Error],
            'partitions': List[V0038Partition]
        }

        self.attribute_map = {
            'meta': 'meta',
            'errors': 'errors',
            'partitions': 'partitions'
        }
        self._meta = meta
        self._errors = errors
        self._partitions = partitions

    @classmethod
    def from_dict(cls, dikt) -> 'V0038PartitionsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0.0.38_partitions_response of this V0038PartitionsResponse.  # noqa: E501
        :rtype: V0038PartitionsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meta(self) -> V0038Meta:
        """Gets the meta of this V0038PartitionsResponse.


        :return: The meta of this V0038PartitionsResponse.
        :rtype: V0038Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: V0038Meta):
        """Sets the meta of this V0038PartitionsResponse.


        :param meta: The meta of this V0038PartitionsResponse.
        :type meta: V0038Meta
        """

        self._meta = meta

    @property
    def errors(self) -> List[V0038Error]:
        """Gets the errors of this V0038PartitionsResponse.

        slurm errors  # noqa: E501

        :return: The errors of this V0038PartitionsResponse.
        :rtype: List[V0038Error]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[V0038Error]):
        """Sets the errors of this V0038PartitionsResponse.

        slurm errors  # noqa: E501

        :param errors: The errors of this V0038PartitionsResponse.
        :type errors: List[V0038Error]
        """

        self._errors = errors

    @property
    def partitions(self) -> List[V0038Partition]:
        """Gets the partitions of this V0038PartitionsResponse.

        partition info  # noqa: E501

        :return: The partitions of this V0038PartitionsResponse.
        :rtype: List[V0038Partition]
        """
        return self._partitions

    @partitions.setter
    def partitions(self, partitions: List[V0038Partition]):
        """Sets the partitions of this V0038PartitionsResponse.

        partition info  # noqa: E501

        :param partitions: The partitions of this V0038PartitionsResponse.
        :type partitions: List[V0038Partition]
        """

        self._partitions = partitions
