# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V0038NodeAllocationSockets(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cores: object=None):  # noqa: E501
        """V0038NodeAllocationSockets - a model defined in Swagger

        :param cores: The cores of this V0038NodeAllocationSockets.  # noqa: E501
        :type cores: object
        """
        self.swagger_types = {
            'cores': object
        }

        self.attribute_map = {
            'cores': 'cores'
        }
        self._cores = cores

    @classmethod
    def from_dict(cls, dikt) -> 'V0038NodeAllocationSockets':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0_0_38_node_allocation_sockets of this V0038NodeAllocationSockets.  # noqa: E501
        :rtype: V0038NodeAllocationSockets
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cores(self) -> object:
        """Gets the cores of this V0038NodeAllocationSockets.

        assignment status of each core by core id in each socket  # noqa: E501

        :return: The cores of this V0038NodeAllocationSockets.
        :rtype: object
        """
        return self._cores

    @cores.setter
    def cores(self, cores: object):
        """Sets the cores of this V0038NodeAllocationSockets.

        assignment status of each core by core id in each socket  # noqa: E501

        :param cores: The cores of this V0038NodeAllocationSockets.
        :type cores: object
        """

        self._cores = cores
