# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.v0038_error import V0038Error  # noqa: F401,E501
from swagger_server.models.v0038_meta import V0038Meta  # noqa: F401,E501
from swagger_server import util


class V0038Errors(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, meta: V0038Meta=None, errors: List[V0038Error]=None):  # noqa: E501
        """V0038Errors - a model defined in Swagger

        :param meta: The meta of this V0038Errors.  # noqa: E501
        :type meta: V0038Meta
        :param errors: The errors of this V0038Errors.  # noqa: E501
        :type errors: List[V0038Error]
        """
        self.swagger_types = {
            'meta': V0038Meta,
            'errors': List[V0038Error]
        }

        self.attribute_map = {
            'meta': 'meta',
            'errors': 'errors'
        }
        self._meta = meta
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'V0038Errors':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0.0.38_errors of this V0038Errors.  # noqa: E501
        :rtype: V0038Errors
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meta(self) -> V0038Meta:
        """Gets the meta of this V0038Errors.


        :return: The meta of this V0038Errors.
        :rtype: V0038Meta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: V0038Meta):
        """Sets the meta of this V0038Errors.


        :param meta: The meta of this V0038Errors.
        :type meta: V0038Meta
        """

        self._meta = meta

    @property
    def errors(self) -> List[V0038Error]:
        """Gets the errors of this V0038Errors.

        slurm errors  # noqa: E501

        :return: The errors of this V0038Errors.
        :rtype: List[V0038Error]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[V0038Error]):
        """Sets the errors of this V0038Errors.

        slurm errors  # noqa: E501

        :param errors: The errors of this V0038Errors.
        :type errors: List[V0038Error]
        """

        self._errors = errors
