# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class V0038Error(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error: str=None, error_number: int=None, description: str=None, source: str=None):  # noqa: E501
        """V0038Error - a model defined in Swagger

        :param error: The error of this V0038Error.  # noqa: E501
        :type error: str
        :param error_number: The error_number of this V0038Error.  # noqa: E501
        :type error_number: int
        :param description: The description of this V0038Error.  # noqa: E501
        :type description: str
        :param source: The source of this V0038Error.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            'error': str,
            'error_number': int,
            'description': str,
            'source': str
        }

        self.attribute_map = {
            'error': 'error',
            'error_number': 'error_number',
            'description': 'description',
            'source': 'source'
        }
        self._error = error
        self._error_number = error_number
        self._description = description
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'V0038Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0.0.38_error of this V0038Error.  # noqa: E501
        :rtype: V0038Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this V0038Error.

        error message  # noqa: E501

        :return: The error of this V0038Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this V0038Error.

        error message  # noqa: E501

        :param error: The error of this V0038Error.
        :type error: str
        """

        self._error = error

    @property
    def error_number(self) -> int:
        """Gets the error_number of this V0038Error.

        Slurm internal error number  # noqa: E501

        :return: The error_number of this V0038Error.
        :rtype: int
        """
        return self._error_number

    @error_number.setter
    def error_number(self, error_number: int):
        """Sets the error_number of this V0038Error.

        Slurm internal error number  # noqa: E501

        :param error_number: The error_number of this V0038Error.
        :type error_number: int
        """

        self._error_number = error_number

    @property
    def description(self) -> str:
        """Gets the description of this V0038Error.

        error description  # noqa: E501

        :return: The description of this V0038Error.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this V0038Error.

        error description  # noqa: E501

        :param description: The description of this V0038Error.
        :type description: str
        """

        self._description = description

    @property
    def source(self) -> str:
        """Gets the source of this V0038Error.

        error source  # noqa: E501

        :return: The source of this V0038Error.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this V0038Error.

        error source  # noqa: E501

        :param source: The source of this V0038Error.
        :type source: str
        """

        self._source = source
