from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class V0038MetaPlugin(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, name=None):  # noqa: E501
        """V0038MetaPlugin - a model defined in OpenAPI

        :param type: The type of this V0038MetaPlugin.  # noqa: E501
        :type type: str
        :param name: The name of this V0038MetaPlugin.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'type': str,
            'name': str
        }

        self.attribute_map = {
            'type': 'type',
            'name': 'name'
        }

        self._type = type
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'V0038MetaPlugin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0_0_38_meta_plugin of this V0038MetaPlugin.  # noqa: E501
        :rtype: V0038MetaPlugin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this V0038MetaPlugin.

          # noqa: E501

        :return: The type of this V0038MetaPlugin.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this V0038MetaPlugin.

          # noqa: E501

        :param type: The type of this V0038MetaPlugin.
        :type type: str
        """

        self._type = type

    @property
    def name(self) -> str:
        """Gets the name of this V0038MetaPlugin.

          # noqa: E501

        :return: The name of this V0038MetaPlugin.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this V0038MetaPlugin.

          # noqa: E501

        :param name: The name of this V0038MetaPlugin.
        :type name: str
        """

        self._name = name
