from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.v0038_node_allocation import V0038NodeAllocation
from openapi_server import util

from openapi_server.models.v0038_node_allocation import V0038NodeAllocation  # noqa: E501

class V0038JobResources(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nodes=None, allocated_cpus=None, allocated_hosts=None, allocated_nodes=None):  # noqa: E501
        """V0038JobResources - a model defined in OpenAPI

        :param nodes: The nodes of this V0038JobResources.  # noqa: E501
        :type nodes: str
        :param allocated_cpus: The allocated_cpus of this V0038JobResources.  # noqa: E501
        :type allocated_cpus: int
        :param allocated_hosts: The allocated_hosts of this V0038JobResources.  # noqa: E501
        :type allocated_hosts: int
        :param allocated_nodes: The allocated_nodes of this V0038JobResources.  # noqa: E501
        :type allocated_nodes: List[V0038NodeAllocation]
        """
        self.openapi_types = {
            'nodes': str,
            'allocated_cpus': int,
            'allocated_hosts': int,
            'allocated_nodes': List[V0038NodeAllocation]
        }

        self.attribute_map = {
            'nodes': 'nodes',
            'allocated_cpus': 'allocated_cpus',
            'allocated_hosts': 'allocated_hosts',
            'allocated_nodes': 'allocated_nodes'
        }

        self._nodes = nodes
        self._allocated_cpus = allocated_cpus
        self._allocated_hosts = allocated_hosts
        self._allocated_nodes = allocated_nodes

    @classmethod
    def from_dict(cls, dikt) -> 'V0038JobResources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v0.0.38_job_resources of this V0038JobResources.  # noqa: E501
        :rtype: V0038JobResources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nodes(self) -> str:
        """Gets the nodes of this V0038JobResources.

        list of assigned job nodes  # noqa: E501

        :return: The nodes of this V0038JobResources.
        :rtype: str
        """
        return self._nodes

    @nodes.setter
    def nodes(self, nodes: str):
        """Sets the nodes of this V0038JobResources.

        list of assigned job nodes  # noqa: E501

        :param nodes: The nodes of this V0038JobResources.
        :type nodes: str
        """

        self._nodes = nodes

    @property
    def allocated_cpus(self) -> int:
        """Gets the allocated_cpus of this V0038JobResources.

        number of assigned job cpus  # noqa: E501

        :return: The allocated_cpus of this V0038JobResources.
        :rtype: int
        """
        return self._allocated_cpus

    @allocated_cpus.setter
    def allocated_cpus(self, allocated_cpus: int):
        """Sets the allocated_cpus of this V0038JobResources.

        number of assigned job cpus  # noqa: E501

        :param allocated_cpus: The allocated_cpus of this V0038JobResources.
        :type allocated_cpus: int
        """

        self._allocated_cpus = allocated_cpus

    @property
    def allocated_hosts(self) -> int:
        """Gets the allocated_hosts of this V0038JobResources.

        number of assigned job hosts  # noqa: E501

        :return: The allocated_hosts of this V0038JobResources.
        :rtype: int
        """
        return self._allocated_hosts

    @allocated_hosts.setter
    def allocated_hosts(self, allocated_hosts: int):
        """Sets the allocated_hosts of this V0038JobResources.

        number of assigned job hosts  # noqa: E501

        :param allocated_hosts: The allocated_hosts of this V0038JobResources.
        :type allocated_hosts: int
        """

        self._allocated_hosts = allocated_hosts

    @property
    def allocated_nodes(self) -> List[V0038NodeAllocation]:
        """Gets the allocated_nodes of this V0038JobResources.

        array of allocated nodes  # noqa: E501

        :return: The allocated_nodes of this V0038JobResources.
        :rtype: List[V0038NodeAllocation]
        """
        return self._allocated_nodes

    @allocated_nodes.setter
    def allocated_nodes(self, allocated_nodes: List[V0038NodeAllocation]):
        """Sets the allocated_nodes of this V0038JobResources.

        array of allocated nodes  # noqa: E501

        :param allocated_nodes: The allocated_nodes of this V0038JobResources.
        :type allocated_nodes: List[V0038NodeAllocation]
        """

        self._allocated_nodes = allocated_nodes
